config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  post 'search', to: 'articles#search'
  get 'search', to: 'articles#search'

  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]
  
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  
  validates :user_id, presence: true
  validates :title, length: { minimum: 4, maximum: 120 }, presence: true
  validates :description, length: { minimum: 4, maximum: 65535}, presence: true
  
  def self.search(search)
    where("title LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%")
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_search, only: [:search]
  before_action :require_user, except: [:index, :show, :search]
  before_action :require_same_user, only: [:destroy, :update, :edit]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    
  end

  # POST /articles
  # POST /articles.json
  def create
     # render plain: params[:article].inspect  # debug.. see whats being passed in
     @article = Article.new(article_params)
     @article.user = current_user
     if @article.save
       flash[:success] = "Article was successfully created!"
       redirect_to article_path(@article)
     else
       flash[:danger] = "Error creating article!"
       render 'new'
     end
  end
  
  def search
    if params[:page] && session[:search]
      # searches each time which is stupid.. oh well..
      @articles = Article.search(session[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 5)
    else
      if params[:search]
        @articles_search = Article.search(params[:search]).order("created_at DESC")
        if @articles_search
          @articles = @articles_search.paginate(page: params[:page], per_page: 5)
        else
          flash[:danger] = "Nothing found for "+params[:search]+"!"
          redirect_to articles_path
        end
      else
        flash[:danger] = "Nothing in search field!"
        redirect_to articles_path
      end
    end
  end
  

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated.'
      redirect_to article_path(@article)
    else
      flash[:danger] = 'Unsuccessful edit!'
      render 'edit'
    
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    old_title = @article.title
    if @article.destroy
      flash[:success] = "Article '#{old_title}' was successfully deleted."
    else
      flash[:danger] = "Article '#{old_title}' could not be deleted!"
    end
    
    redirect_to articles_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    def set_search
      if params[:search] 
        session[:search] = params[:search]
      end
      if session[:search]
        @articles_search = Article.search(params[:search]).order("created_at DESC")
      else
        flash[:danger] = "No search param found!"
        redirect_to articles_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles!"
        redirect_to root_path
      end
    end
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<% if obj.count < 1 %>
    <div class="well center">No articles found!  <%= link_to "Create a new one?", new_article_path %></div>
<% end %>
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to truncate(article.title,length:80)+(" .." if article.title.length > 80), article_path(article) %> 
        </div>
        <div class="article-user">
          <small>Created by: </small><%= link_to truncate(article.user.username,length:40), articles_path(article.user) %> 
        </div>
        <div class="article-body">
          <%= truncate(article.description,length:120)+(" .." if article.description.length > 80) %>
          
          <div class="article-meta-details">
            Created: <%= time_ago_in_words(article.created_at) %> ago, 
            Last updated: <%= time_ago_in_words(article.updated_at) %> ago
          </div>
        </div>
        <% if article.categories.any? %>
          <p>Categories: <%= render article.categories %></p>
        <% end %>
        <% if logged_in? and (current_user == article.user || current_user.admin?)  %>
          <div class="article-actions">
            <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete this article", article_path(article), method: :delete, data: { 
                confirm: "Are you sure you wanto delete this article?" }, class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>   
<% end %>

<br>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-xs-12">

    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title  %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article" , autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all.sort_by(&:name), :id, :name do |cb|  %>
              <% cb.label(class: "checkbox-inline input_checkbox") { cb.check_box(class: "checkbox") } + cb.text  %>
            <% end %>
          </div>
        </div>
      </div>
        
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-2">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
        <div class="col-sm-2">
          <%= link_to "Cancel and return", articles_path, class: 'btn btn-danger btn-lg' %>
        </div>
      </div>
    
        
    <% end %>



  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Editing Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Newest Alpha articles</h1>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Be creative!</h1>

<%= render 'form' %>

app/views/articles/search.html.erb
<h1 align="center">Search results: '<%= session[:search] %>'</h1>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
  <% will_paginate %>
</div>
<%= hidden_field_tag :search, params[:search] %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
  <% if @article.user %>   
    <div align="center">
      <ul class="listing">
        <div class="row">
          <li class="center small">Created by:</li>
          <div class="col-md-4 col-md-offset-4 center">
            <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
            <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
            <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
          </div>
        </div>
      </ul>
    </div>
  <% end %>
  
  <div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %> </p>
  <% end %>
  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %> 
      <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete this article", article_path(@article), method: :delete, data: { confirm: "Are you sure you wanto delete this article?" }, class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
  </div>
  
  