config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  post 'search', to: 'articles#search'
  get 'search', to: 'articles#search'

  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories, except: [:destroy]
  
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>Copyright &copy 2018 <a href="http://www.xddev.net">xddev.net</a> by Alex Datsko</small>

    <nav><ul><li><%= link_to "About", about_path, id: "about" %></li></ul></nav>

  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <%= link_to "ALPHABLOG", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li id="link2"><%= link_to "Users", users_path, id: "link2" %></li>
      <% if logged_in? %>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="link2">Articles <span class="caret"></span></a>
        <ul class="dropdown-menu">
        <% if logged_in? %> 
          <li id="link2"><%= link_to "New Article", new_article_path, id: "link2" %></li>
          <li id="link2"><%= link_to "View your Articles", user_path(current_user), id: "link2" %></li>
        <% end %>
        <li id="link2"><%= link_to "View all Articles", articles_path, id: "link2" %></li>
        </ul>
        </li>
      <% end %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="link2">Categories <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "All Categories", categories_path %></li>
          <li role="separator" class="divider" id="link2"></li>
          <% Category.all.each do |category| %>
            <li><%= link_to "#{category.name}", category_path(category) %></li>
          <% end %>
          <% if logged_in? and current_user.admin? %>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Create New Category", new_category_path %></li>
          <% end %>
        </ul>
      </li>
      </ul>
      
      <%= form_tag(search_path, { method: :post, class: 'navbar-form navbar-left' } ) do %>
        <%= text_field_tag :search, params[:search], class: 'form-control' %>
        <%= submit_tag 'Search', name: nil, class: "btn btn-default" %>
      <% end %>
    
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li><%= link_to 'Log out', logout_path, method: :delete %></li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="link2">Your Profile<%= " (admin)" if current_user.admin? %><span class="caret"></span></a>
        <ul class="dropdown-menu">
        <li><%= link_to "Edit your profile", edit_user_path(current_user), id: "link2" %></li>
        <li><%= link_to "View your profile", user_path(current_user), id: "link2" %></li>
        <li role="separator" class="divider" id="link2"></li>
        </ul>
        </li>
      <% else %>
        <li><%= link_to 'Log in', login_path, id: "link2" %></li>
        <li><%= link_to 'Sign up', signup_path, id: "link2" %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlogCentauri</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>

    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    
    <% if !Rails.env.production?  %> 
      <%= debug(params) %>
      <%= debug session if false %> 
    <% end %>
  </body>
</html>